export const PERMISSION_MODULE_CATALOG = [
  { id: "tracing", label: "Seguimiento" },
  { id: "ingenieria_archivos", label: "Control Informes" },
  { id: "clientes", label: "Clientes" },
  { id: "proyectos", label: "Proyectos" },
  { id: "cotizadora", label: "Cotizadora" },
  { id: "programacion", label: "Programación" },
  { id: "recepcion", label: "Recepción Probetas" },
  { id: "verificacion_muestras", label: "Verificación Probetas" },
  { id: "compresion", label: "F. Probetas" },
  { id: "humedad", label: "Humedad Suelo" },
  { id: "cont_humedad", label: "Humedad AG" },
  { id: "humedad_complete_demo", label: "Humedad Multitab" },
  { id: "cbr", label: "CBR" },
  { id: "proctor", label: "Proctor" },
  { id: "llp", label: "Límite" },
  { id: "gran_suelo", label: "Gran Suelo" },
  { id: "gran_agregado", label: "Gran Agregado" },
  { id: "cont_mat_organica", label: "M. Orgánica" },
  { id: "terrones_fino_grueso", label: "Terrones" },
  { id: "azul_metileno", label: "Azul Metileno" },
  { id: "part_livianas", label: "Part. Livianas" },
  { id: "imp_organicas", label: "Imp. Orgánicas" },
  { id: "sul_magnesio", label: "Sulf. Magnesio" },
  { id: "angularidad", label: "Angularidad" },
  { id: "abra", label: "Abrasión Mayores" },
  { id: "abrass", label: "Abrasión Menores" },
  { id: "peso_unitario", label: "Peso Unitario" },
  { id: "tamiz", label: "Malla 200" },
  { id: "planas", label: "Planas" },
  { id: "caras", label: "Caras" },
  { id: "equi_arena", label: "E. Arena" },
  { id: "ge_fino", label: "GE Fino" },
  { id: "ge_grueso", label: "GE Grueso" },
  { id: "cd", label: "Corte Directo" },
  { id: "ph", label: "PH Suelo" },
  { id: "cloro_soluble", label: "Cloruro Suelo" },
  { id: "sales_solubles", label: "Sales Suelo" },
  { id: "sulfatos_solubles", label: "Sulfato Suelo" },
  { id: "compresion_no_confinada", label: "Compresión No Confinada" },
  { id: "laboratorio", label: "Control Laboratorio" },
  { id: "oficina_tecnica", label: "Control Oficina Técnica" },
  { id: "comercial", label: "Control Comercial" },
  { id: "administracion", label: "Control Administración" },
  { id: "usuarios", label: "Usuarios" },
  { id: "permisos", label: "Matriz de Permisos" },
  { id: "auditoria", label: "Auditoría" },
  { id: "configuracion", label: "Configuración" },
] as const

export type PermissionModuleId = (typeof PERMISSION_MODULE_CATALOG)[number]["id"]
