# Stage 1: Dependencies
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./
RUN npm ci

# Stage 2: Builder
FROM node:20-alpine AS builder
WORKDIR /app

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Set build-time environment variables
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_COTIZADOR_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_VERIFICACION_FRONTEND_URL
ARG NEXT_PUBLIC_RECEPCION_FRONTEND_URL
ARG NEXT_PUBLIC_PROGRAMACION_URL
ARG NEXT_PUBLIC_PROGRAMACION_LABORATORIO_URL
ARG NEXT_PUBLIC_PROGRAMACION_OFICINA_TECNICA_URL
ARG NEXT_PUBLIC_PROGRAMACION_COMERCIAL_URL
ARG NEXT_PUBLIC_PROGRAMACION_ADMINISTRACION_URL
ARG NEXT_PUBLIC_COMPRESION_FRONTEND_URL
ARG NEXT_PUBLIC_CD_FRONTEND_URL
ARG NEXT_PUBLIC_PH_FRONTEND_URL
ARG NEXT_PUBLIC_CLORO_SOLUBLE_FRONTEND_URL
ARG NEXT_PUBLIC_SALES_SOLUBLES_FRONTEND_URL
ARG NEXT_PUBLIC_SULFATOS_SOLUBLES_FRONTEND_URL
ARG NEXT_PUBLIC_COMPRESION_NO_CONFINADA_FRONTEND_URL

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_COTIZADOR_URL=$NEXT_PUBLIC_COTIZADOR_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_VERIFICACION_FRONTEND_URL=$NEXT_PUBLIC_VERIFICACION_FRONTEND_URL
ENV NEXT_PUBLIC_RECEPCION_FRONTEND_URL=$NEXT_PUBLIC_RECEPCION_FRONTEND_URL
ENV NEXT_PUBLIC_PROGRAMACION_URL=$NEXT_PUBLIC_PROGRAMACION_URL
ENV NEXT_PUBLIC_PROGRAMACION_LABORATORIO_URL=$NEXT_PUBLIC_PROGRAMACION_LABORATORIO_URL
ENV NEXT_PUBLIC_PROGRAMACION_OFICINA_TECNICA_URL=$NEXT_PUBLIC_PROGRAMACION_OFICINA_TECNICA_URL
ENV NEXT_PUBLIC_PROGRAMACION_COMERCIAL_URL=$NEXT_PUBLIC_PROGRAMACION_COMERCIAL_URL
ENV NEXT_PUBLIC_PROGRAMACION_ADMINISTRACION_URL=$NEXT_PUBLIC_PROGRAMACION_ADMINISTRACION_URL
ENV NEXT_PUBLIC_COMPRESION_FRONTEND_URL=$NEXT_PUBLIC_COMPRESION_FRONTEND_URL
ENV NEXT_PUBLIC_CD_FRONTEND_URL=$NEXT_PUBLIC_CD_FRONTEND_URL
ENV NEXT_PUBLIC_PH_FRONTEND_URL=$NEXT_PUBLIC_PH_FRONTEND_URL
ENV NEXT_PUBLIC_CLORO_SOLUBLE_FRONTEND_URL=$NEXT_PUBLIC_CLORO_SOLUBLE_FRONTEND_URL
ENV NEXT_PUBLIC_SALES_SOLUBLES_FRONTEND_URL=$NEXT_PUBLIC_SALES_SOLUBLES_FRONTEND_URL
ENV NEXT_PUBLIC_SULFATOS_SOLUBLES_FRONTEND_URL=$NEXT_PUBLIC_SULFATOS_SOLUBLES_FRONTEND_URL
ENV NEXT_PUBLIC_COMPRESION_NO_CONFINADA_FRONTEND_URL=$NEXT_PUBLIC_COMPRESION_NO_CONFINADA_FRONTEND_URL

# Build the application
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# Stage 3: Runner
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create non-root user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy necessary files
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# Set correct permissions
RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Add healthcheck (robust checking)
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://127.0.0.1:3000/ || exit 1

# Next.js standalone entry point
CMD ["node", "server.js"]
